name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2']
        include:
          - php: '8.2'
            option: '--ignore-platform-req=php+'
    services:
      db:
        image: mysql:8.0.23
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: spatial_test
          MYSQL_ROOT_PASSWORD: password
    name: Test PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up php ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: mbstring, dom, fileinfo, pdo, pcntl
          coverage: none
      - run: composer install ${{ matrix.option }}
      - name: run test
        run: vendor/bin/phpunit
